### ISSUE TITLE
Hatred rules

### ISSUE THREAD

**Issue by mcclowes** [hammerheim-game/hammerheim-rules#1]
3 options:
- Re-roll to hit in first turn of combat
- +1 to injury rolls
- you can hit people you Hate when they're on the ground, even if there are standing up enemies you could otherwise attack

**Comment by Yther** [comment]
I'm very much in favour of the first option. It keeps to what both the Mordheim and Warhammer books say and will cause the least amount of conflict with unforeseen hatred-related rules from the Warhammer books later down the line.

**Comment by mcclowes** [comment]
Agreed @Yther
