### ISSUE TITLE
Border Town Burning Integration

### ISSUE THREAD

**Issue by Yther** [hammerheim-game/hammerheim-rules#19]
Glossary at the end
New skills implemented (Including BTB skills)
Last Orders added

**Comment by Yther** [comment]
Just the reference sheet to go, Last Order + Skills added (Your Beastmaster skill is now there Max!)

**Comment by mcclowes** [comment]
Which of these warbands are we going to integrate?

**Comment by Yther** [comment]
I wasn't planning on integrating any of them, just doing the reference sheet & skills & some scenarios. I've finished doing that now (though reference sheet needs some touching up) so I think this can be closed.

**Comment by mcclowes** [comment]
I'd like to put in Battle Monks, the Lich, and anything else you think works. Definitely not The Black Dwarves though.

**Comment by Yther** [comment]
Alright then, I'll put those factions in. Probably Marauders too, then rework Cult of The Possessed to give it more of that 'mutanty' feel. I've reworked their magic to make it much more 'all power demands sacrifice'. 

I also want to put in a Stirland faction because dammit the game needs more Humans. I think then I'll stop.

**Comment by mcclowes** [comment]
I'll make separate Issues for each warband and then close this
