### ISSUE TITLE
One use items suck

### ISSUE THREAD

**Issue by mcclowes** [hammerheim-game/hammerheim-rules#21]
We should look at reworking anything that's one use. When you're playing 20 games in a campaign, rather than 4, there is really no point in buying something for one games

**Comment by Yther** [comment]
I can agree with that. Smoke Bombs are interesting enough that I think they're fine, since 5g for something pretty gamechanging is reasonable - but for poisons etcetera that cost 30 gold and last for one game? That's pretty nutty. I'll make that my next task.
