### ISSUE TITLE
Catchup System High-Risk Flaw

### ISSUE THREAD

**Issue by Yther** [hammerheim-game/hammerheim-rules#31]
The catchup system at the moment is disproportionately punitive towards small warbands. D3 injuries is a big deal for Heroheim, but totally laughably easy to disregard as a large warband (plus the value of +1 bonus experience on a group of henchmen is greater than +1 bonus experience on a hero).

Proposed rework that doing high risk means you take injuries equal to your minimum rout threshold that you can allocate freely around your warband, and bonus experience can only go on your heroes. A much closer approximation of what would happen to a warband in a game. (suspect the current system will be kinda strong AF for my goblins in particular).

**Comment by mcclowes** [comment]
I like your thinking. I've been thinking you should get rid of high risk, but improve the standard.
- 1xp to each member
- 1 injury randomly distributed
- 1 xp to a hero
- 25 gold

Something like that.

**Comment by Yther** [comment]
Something like that could work, I'd be pretty happy with it. I think 25g is too little though, I mean low risk atm is 30g. I wouldn't pay 5g to have one of my guys injured and to gain an extra bonus xp - and even 30g feels low.

What about 1xp to everyone, a bonus 1xp to add to whoever you want, and 35gold? You've not lost anyone but that's still not a huge haul, that's like rolling 3 exploration dice after the game. Its quick, easy to remember, and nobody dies because of things happening offscreen (which just feels awful).

**Comment by mcclowes** [comment]
Yeah that sounds good. I forgot that you do already earn gold from the low risk lol, I thought 25g would be a buff

Max

maxcc@me.com (mailto:maxcc@me.com)
+44 (0) 7976 136 097
