### ISSUE TITLE
American spelling

### ISSUE THREAD

**Issue by Yther** [hammerheim-game/hammerheim-rules#46]
Replace "Armor" with "Armour"
Replace "Valor" with "Valour"

Probably other words too. Will add to this issue as they come up.

**Comment by mcclowes** [comment]
I actually think the whole book should probably be in american spelling, but as most of it seems to be british spelling I will change these words

**Comment by Yther** [comment]
https://gifsound.com/?gif=24.media.tumblr.com/b9c373824cae3737e32251da57ae9413/tumblr_mgtthn1J9e1rivwfuo1_500.gif&v=x0I6mhZ5wMw

How dare you.
