### ISSUE TITLE
Model/Warrior

### ISSUE THREAD

**Issue by mcclowes** [hammerheim-game/hammerheim-rules#9]
Consistency around referring to a model needed. Currently interchangably referred to as a warrior or model

**Comment by Yther** [comment]
It's possibly worth differentiating between the two, particularly for scenarios like Wyrdstone hunts where you wouldn't expect a non-warrior model like a Chaos Spawn or a Zombie to be able to understand the importance of retrieving valuable items. It would be useful perhaps to distinguish a _warrior_ as a warband member capable of gaining experience, while a model includes everything on an independent base (so a chariot is considered one model, not a chassis, two horses, and two crew). I can then rewrite the scenarios to add more clarity about who can/can't perform certain actions.

**Comment by mcclowes** [comment]
Interesting! I like this use of Warrior as a keyword. At the moment it seems to be more to add flavour to a rule description

Max

maxcc@me.com (mailto:maxcc@me.com)
+44 (0) 7976 136 097
